// 価値観データ（キーワードと説明）
export const VALUES_DATA = [
  { keyword: '誠実', description: '嘘をつかず、真心を持って接する' },
  { keyword: '勇気', description: '恐れずに一歩踏み出す' },
  { keyword: '自律', description: '自分を律し、甘えない' },
  { keyword: '知恵', description: '深い知識と経験を活かす' },
  { keyword: '平穏', description: '心の安らぎを保つ' },
  { keyword: '忍耐', description: '苦しい時も耐え忍ぶ' },
  { keyword: '謙虚', description: '慢心せず、常に学ぶ姿勢を持つ' },
  { keyword: '気品', description: '洗練された振る舞い' },
  { keyword: '純粋', description: '汚れのない素直な心' },
  { keyword: '自尊心', description: '自分を大切に思う' },
  { keyword: '挑戦', description: '新しいことに挑み続ける' },
  { keyword: '情熱', description: '熱意を持って取り組む' },
  { keyword: '創造', description: 'ゼロから新しいものを生む' },
  { keyword: '冒険', description: '未知の世界を探索する' },
  { keyword: '規律', description: 'ルールや習慣を守る' },
  { keyword: '一貫性', description: '言動に矛盾がない' },
  { keyword: '卓越', description: '最高の結果を追求する' },
  { keyword: '好奇心', description: '何にでも興味を持つ' },
  { keyword: '生産性', description: '効率よく成果を出す' },
  { keyword: '不屈', description: '何度倒れても立ち上がる' },
  { keyword: '慈愛', description: '深い愛情を持って慈しむ' },
  { keyword: '貢献', description: '誰かの役に立つ' },
  { keyword: '信頼', description: '信じ、信じられる関係' },
  { keyword: '正義', description: '正しい道を通す' },
  { keyword: '寛容', description: '他者の違いを受け入れる' },
  { keyword: '調和', description: '全体のバランスを保つ' },
  { keyword: '忠誠', description: '組織や人に尽くす' },
  { keyword: '共感', description: '相手の気持ちに寄り添う' },
  { keyword: '礼節', description: '礼儀正しく振る舞う' },
  { keyword: '連帯', description: '仲間と協力し合う' },
  { keyword: '自由', description: '何にも縛られない' },
  { keyword: '個性', description: '自分だけの特性を磨く' },
  { keyword: '柔軟', description: '変化に臨機応変に対応する' },
  { keyword: '遊び心', description: '楽しむ余裕を忘れない' },
  { keyword: '本質', description: '表面ではなく核心を突く' },
  { keyword: '開放', description: '心を開き、隠し事をしない' },
  { keyword: '独創性', description: '独自の発想を大切にする' },
  { keyword: 'シンプル', description: '複雑さを削ぎ落とす' },
  { keyword: '美意識', description: '自分なりの美しさを追う' },
  { keyword: '自立', description: '他者に依存せず生きる' },
  { keyword: '健康', description: '心身の健やかさを保つ' },
  { keyword: '感謝', description: '当たり前のことに有難みを感じる' },
  { keyword: '安定', description: '変化を抑え、平和に過ごす' },
  { keyword: '豊かさ', description: '精神的、物質的な満足' },
  { keyword: '伝統', description: '受け継がれてきたものを守る' },
  { keyword: '希望', description: '未来を明るく信じる' },
  { keyword: 'ユーモア', description: '笑いで困難を乗り越える' },
  { keyword: '持続可能性', description: '長く続けられる道を選ぶ' },
  { keyword: '休息', description: '自分を労わる時間を取る' },
  { keyword: '幸福', description: '自分にとっての幸せを追求する' },
];

// 呼吸リズムの選択肢（秒）
export const RHYTHM_OPTIONS = [3, 6, 9];

// 呼吸時間の選択肢（秒）
export const DURATION_OPTIONS = [60, 180, 300];
